config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end
  
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'

  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => 'reload' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <!-- <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %> -->
    <span class="title">Depot</span>
    <span class="title"><%= @page_title %></span>
  </div>
  <div id="columns">
    <div id="side">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
      <% end %>

      <ul>
        <li><%= link_to 'Home', store_index_url %></li>
      </ul>

      <ul>
        <% if session[:user_id] %>
          <li><%= link_to 'Orders',   orders_path   %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Admin Login', login_path %></li>
        <% end %>
      </ul>

    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>